import Head from 'next/head'
import Image from 'next/image';
import Infographics from '../components/Infographics';
import Header from '../components/Header';
import RelatedArticles from '../components/RelatedArticles';
import FrequentQuestions from '../components/FrecuentQuestions';
import Media from '../components/Media';
import Footer from '../components/Footer';
import { fetchArticles, fetchRelatedPosts } from '../data/api';
import mainImage from '../public/images/main.png';
import { Fragment } from 'react';
import GuidedVisit from '../components/GuidedVisit';
import staticData from '../data/static.json';


export default function Index({ articles, keywords, relatedPosts  }) {
  return (
    <Fragment>
      <Head>
        <title>Código de Familias | elTOQUE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header articles={articles} keywords={keywords} />
      <main className='main'>
        <div className='main__image'>
          <Image src={mainImage} alt=""></Image>
        </div>
        <div className='main__content'>
          <GuidedVisit articles={articles} />
          <Media/>
          <Infographics/>
          <RelatedArticles relatedPosts={relatedPosts}/>
          <FrequentQuestions/>
        </div>
      </main>
      <Footer />
    </Fragment>
  )
}

export async function getStaticProps(context) {
  const articles = await fetchArticles();
  const relatedPosts = await fetchRelatedPosts();
  const { keywords } = staticData;
  return {
    props: {
      articles,
      keywords,
      relatedPosts
    }
  }
}